### ISSUE TITLE
Read current font settings and add them to fontList once installed

### ISSUE THREAD

**Issue by zoubingwu** [Zev18/font-randomizer#2]
Currently this plugin will overwrite the fontFamily setting on install, and all previous font setting will be gone, it took me a while to restore it back 😂

**Comment by Zev18** [comment]
Just pushed a fix. Should now only change the first font in fontFamily instead of the entire string, but it will make edits in order to avoid any duplicates.

**Comment by NinjaZMY** [comment]
# Unfortunate to tell you that your fixes do not fix the issue itself but a small part of it. 

0) The least required fix is to at least, make your custom fontList create itself and assign to itself at least one value, or zero value if zero value is supported  ( if there's 0 settings from settings.json ) 

1) to push things further you need to be able to read system installed fonts and automatically add them to the extension fontList 
which will automatically upgrade your extension into a top-tier font extension but that is unfortunately is still unavailable at the moment

**Comment by Zev18** [comment]
Dude, you are talking about a different issue. I fixed everything wrong with the issue that op described.
